### ISSUE TITLE
No Grid gap on the left

### ISSUE THREAD

**Issue by lenmarbra** [lenmarbra/lenmarbra.github.io#10]
https://github.com/lenmarbra/lenmarbra.github.io/blob/20a099c1de5f3df2de9e463600c33a447f575a5a/css/layouts.css#L87

@gorazd How come the grid-gap does not apply to the left. See screendump, https://www.dropbox.com/s/8q4cb1cf20gvl56/grid-gap-on-right.png?dl=0

**Comment by lenmarbra** [comment]
@gorazd new (correct) link above

**Comment by gorazd** [comment]
Hey, grid gap creates space only between the grid cells.

Add padding (same value) to the grid container.

**Comment by lenmarbra** [comment]
Ok, thanks @gorazd
