### ISSUE TITLE
Titles in your html files

### ISSUE THREAD

**Issue by gorazd** [lenmarbra/lenmarbra.github.io#11]
Please check your titles:
`<title>Document</title>`

A good title for your homepage:
Maria Bramer Portfolio
for your project page:
Magis redesign - Maria Bramer Portfolio

**Comment by lenmarbra** [comment]
Nice, thank you!

**Comment by gorazd** [comment]
Hey, don't close the issue until it's fixed and pushed to the repo :)

**Comment by lenmarbra** [comment]
Ok, now it should be pushed also :)
