### ISSUE TITLE
line break in h1 - don't want it

### ISSUE THREAD

**Issue by lenmarbra** [lenmarbra/lenmarbra.github.io#3]
https://github.com/lenmarbra/lenmarbra.github.io/blob/8bc3c50d4390d836b183417e04ed67d6c8d3e593/new/CosimoVeneziano.html#L40

Hey @gorazd , how can i get rid of this line break. I have written the word Cosimo Veneziano wich i want displayed on one line only, not two as it is right now. What am i messing up on?

**Comment by lenmarbra** [comment]
even bofore i had added the image i had the same problem. [/new/CosimoVeneziano.html](url)

**Comment by gorazd** [comment]
Try to inspect the element. There is not enough space in the grid cell to fit the text.

You either make the font size smaller, the grid cell bigger, or keep the line break.

**Comment by lenmarbra** [comment]
Solved
