### ISSUE TITLE
Image not showing

### ISSUE THREAD

**Issue by lenmarbra** [lenmarbra/lenmarbra.github.io#5]
https://github.com/lenmarbra/lenmarbra.github.io/blob/4375336ad1e54e1fa285f83b6e99c3e9a1cedcaf/css/ux.css#L137

Hi, this image is not showing. I've tried different ways: adding it in the html, used the grid to position it, used the position: absolute, tried changing it with other images.. etc etc. It's stopping me from adding the rest of the content for this page.

**Comment by gorazd** [comment]
Inspect your code, see why it's not loading:
https://www.dropbox.com/s/7sh1cw4rkmunc5k/Screenshot%202020-05-15%2008.11.45.png?dl=0

Also optimise your images, I see you have a 2.5MB image in your homepage:
https://lenmarbra.github.io/images/ux/smallImage_magis.png
is the size correct, are you optimizing the weight?

**Comment by lenmarbra** [comment]
Solved
