### ISSUE TITLE
Text displayed on a narrow vertical line

### ISSUE THREAD

**Issue by lenmarbra** [lenmarbra/lenmarbra.github.io#6]
https://github.com/lenmarbra/lenmarbra.github.io/blob/ffb5f8db35249ecaa7397c8cfb26b8efaf0cc1ae/css/ux.css#L131

I'm trying to adjust this text (see screendump on link below) by changing the position, but not managing. 
[https://www.dropbox.com/s/bli27s2ze6ka63s/Screenshot%202020-05-15%20at%2021.25.23.png?dl=0](url)

**Comment by gorazd** [comment]
What page is this on? I tried the Magis project but can't find the `.text` element.

**Comment by lenmarbra** [comment]
solved
