### ISSUE TITLE
Trying Grid for ux2 page

### ISSUE THREAD

**Issue by lenmarbra** [lenmarbra/lenmarbra.github.io#7]
https://github.com/lenmarbra/lenmarbra.github.io/blob/0607a1a041326b626186a46e81d4dbcc028bbff5/css/ux2.css#L59

Hey @gorazd, hope you had a good weekend! 

I'm trying the grid for file ux2.html/ux2.css as I cannot make it work with flexbox and positioning (files: ux.html/ux.css). 

If I can only get the grid right I think i can manage with this. However now, the rows are messing it up. I've started by only adding the title and an image, to get the grid right first. And then I will add the rest of the content. Can you see what i'm doing wrong with the grid?

For me it also looks different in chrome vs. firefox right now.

**Comment by lenmarbra** [comment]
And for the rows, i'v tried different numbers and measurements, not just 4 as it is right now.

**Comment by lenmarbra** [comment]
https://www.dropbox.com/s/nn3m9ur0urcqw2w/Screenshot%202020-05-17%20at%2009.45.48.png?dl=0

https://www.dropbox.com/s/6zxgu94397nova7/Screenshot%202020-05-17%20at%2009.45.41.png?dl=0

**Comment by lenmarbra** [comment]
I you can look into this today I would highly appreciate it, as I have classes all day on Monday (i'm in the visuals program too).

**Comment by gorazd** [comment]
Hey, can I see how it should look like?

I created a ux branch and will let you know when to merge it.

**Comment by lenmarbra** [comment]
https://lenmarbra.github.io/ux2.html

Css code: 
https://github.com/lenmarbra/lenmarbra.github.io/blob/master/css/ux2.css

html code:
https://github.com/lenmarbra/lenmarbra.github.io/blob/master/ux2.html

**Comment by lenmarbra** [comment]
forgot to ping. @gorazd

**Comment by lenmarbra** [comment]
Yes, i guess it would be better to code this on branch. but i made a workaround and created new files in the master instead. Not sure how to use the branches.

**Comment by gorazd** [comment]
I was wondering where i can see the layout you are trying to implement?

**Comment by lenmarbra** [comment]
Ah, ok. Here: https://www.dropbox.com/s/2ojym9ccw4zgkfu/magis.png?dl=0

**Comment by lenmarbra** [comment]
Ignore the lines. (meant to be the grid)

**Comment by lenmarbra** [comment]
Here's all of it (so far) https://xd.adobe.com/view/73bb53eb-8c13-40a3-796c-d02475856bfe-058a/

Magis is on 2nd or 3rd. 
@gorazd

**Comment by lenmarbra** [comment]
so, i'm aiming to have the start page, magis, and cosimo veneziano done by wednesday.

**Comment by lenmarbra** [comment]
And the css grid layout is in the css: 

#wrapper{
  display: grid;
  grid-template-columns: 112px 550px 112px 550px 112px;
  grid-template-rows: minmax(150px, auto);
  width: 100vp;
  /* height: 500em; */
  /* grid-template-areas: 
  ". . . . ."
  ". title title . ."
  ". . hero hero hero"
  ". . hero hero hero."
  ". . hero hero hero"
  ". . . . ." */
}

And here's a sketch of it. https://www.dropbox.com/s/4a6ko3arqvejeig/layout%3Agrid.png?dl=0

@gorazd

**Comment by lenmarbra** [comment]
@gorazd for notification - just updated the grid-sketch a little and thus change the link above.

**Comment by lenmarbra** [comment]
Got a working gird now, i think i can use for all landing pages.

**Comment by gorazd** [comment]
It looks good but breaks at one point:
https://www.dropbox.com/s/exv79plil7f8mpd/Screenshot%202020-05-18%2007.38.55.png?dl=0
