### ISSUE TITLE
Images displayed wrong

### ISSUE THREAD

**Issue by lenmarbra** [lenmarbra/lenmarbra.github.io#9]
https://github.com/lenmarbra/lenmarbra.github.io/blob/20a099c1de5f3df2de9e463600c33a447f575a5a/css/layouts.css#L294

@gorazd  Any advice on how I can make these two images, grid-img1 and grid-img2, display correctly. That is, covering the whole area (or at least the full width) but still displaying the whole image.

**Comment by lenmarbra** [comment]
@gorazd adding a screendump. https://www.dropbox.com/s/ef5efs95v984ml2/grid-img-area.png?dl=0

**Comment by gorazd** [comment]
I don't see them. Are the URLs correct?

https://lenmarbra.github.io/images/layouts/grid1.png
https://lenmarbra.github.io/images/layouts/grid2.png

**Comment by lenmarbra** [comment]
@gorazd   Yes, they are correct, and the images are there (not displayed in a very nice way only). They are on this page http://127.0.0.1:5502/layouts.html under the heading "Grid"

**Comment by gorazd** [comment]
Not online:
https://www.dropbox.com/s/9echkvz5qdplaom/Screenshot%202020-05-19%2017.49.44.png?dl=0

The link you sent me is your local copy. Make sure you pushed your code to git.

**Comment by lenmarbra** [comment]
Ok, now they should be there. https://lenmarbra.github.io/layouts.html

**Comment by lenmarbra** [comment]
and the tag, @gorazd

**Comment by gorazd** [comment]
I can see them now.

Why don't you move them to your HTML instead of using them as background images.
They are part of your content.

**Comment by lenmarbra** [comment]
Fixed
